version: "3.8"

services:
  client:
    build:
      context: client
      dockerfile: Dockerfile

    ports: # Port binding to host from docker container
      - 3000:3000 # Bind port 3000 of host to 3000 of container

    container_name: client-docker

  api:
    build:
      context: server
      dockerfile: Dockerfile
      
    environment:
      - PORT=$API_PORT
    ports:
      - $API_PORT:$API_PORT

    container_name: api-docker
