name: "Backend Call"

on:
  schedule:
    - cron: "0/15 0/1 * * *"

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Update & install
        run: sudo apt-get update && sudo apt-get -y install wget

      - name: Open site
        run: wget "https://messagespace-server.azurewebsites.net"
