name: "Open web page"

on:
  schedule:
    - cron: "0/15 0/1 * * *"

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Open site
        run: apt-get update && apt-get -y install wget && wget "https://message-space.web.app"
